env:
  browser: true
  node: true
  jest: true

extends:
  - airbnb
  - airbnb-typescript
  - next/core-web-vitals
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended

ignorePatterns:
  - .next/
  - .eslintrc.yaml
  - .gitignore
  - .prettierrc.yaml
  - node_modules/
  - public/
  - next-env.d.ts
  - next.config.mjs
  - package.json
  - package-lock.json
  - tsconfig.json

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaFeatures:
    jsx: true
  project: 'tsconfig.json'
  sourceType: module
  tsconfigDirRoot: __dirname

plugins:
  - '@typescript-eslint'
  - 'prettier'

root: true

rules:
  # TypeScript
  '@typescript-eslint/no-empty-interface': warn
  '@typescript-eslint/no-empty-function': warn
  '@typescript-eslint/no-explicit-any': warn
  '@typescript-eslint/no-shadow': warn
  '@typescript-eslint/no-unused-expressions': warn
  '@typescript-eslint/no-unused-vars': warn
  '@typescript-eslint/no-use-before-define': off
  '@typescript-eslint/no-useless-constructor': warn
  # import
  'import/extensions': off
  'import/no-extraneous-dependencies': off
  'import/prefer-default-export': warn
  # React
  'react/no-unknown-property': [error, { ignore: ['css'] }]
  'react/no-unused-prop-types': off
  'react/jsx-filename-extension': [error, { extensions: ['.tsx', '.jsx'] }]
  'react/jsx-no-useless-fragment': off
  'react/jsx-props-no-spreading': off
  'react/jsx-uses-react': off
  'react/react-in-jsx-scope': off
  'react/require-default-props': off
