env:
  node: true
  jest: true

extends:
  - airbnb-base
  - airbnb-typescript/base
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended

ignorePatterns:
  - .eslintrc.yaml
  - .gitignore
  - .nvmrc
  - .prettierrc.yaml
  - dist/
  - envs/
  - logs/
  - node_modules/
  - license
  - nestjs-cli.json
  - package.json
  - pnpm-lock.yaml
  - tsconfig.json
  - tsconfig.build.json

parser: '@typescript-eslint/parser'

parserOptions:
  project: true
  project: 'tsconfig.json'
  sourceType: 'module'
  tsconfigDirRoot: __dirname

plugins:
  - '@typescript-eslint'
  - prettier

root: true

rules:
  '@typescript-eslint/no-empty-interface': warn
  '@typescript-eslint/no-empty-function': warn
  '@typescript-eslint/no-explicit-any': warn
  '@typescript-eslint/no-shadow': warn
  '@typescript-eslint/no-unused-expressions': warn
  '@typescript-eslint/no-unused-vars': warn
  '@typescript-eslint/no-use-before-define': off
  '@typescript-eslint/no-useless-constructor': warn
  'class-methods-use-this': off
  'import/extensions': off
  'import/prefer-default-export': warn
